routes/web.php
<?php

use App\Http\Controllers\Admin\HomePage\BannerController;
use App\Http\Controllers\Admin\HomePage\VenueController;
use App\Http\Controllers\Admin\HomePage\MessageController;
use App\Http\Controllers\Admin\Menu\MenuController;
use App\Http\Controllers\Admin\Menu\SubMenuController;
use App\Http\Controllers\Admin\Menu\PageController;
use App\Http\Controllers\Admin\DesignationController;
use App\Http\Controllers\Admin\DonortypeController;
use App\Http\Controllers\Admin\InviteeController;
use App\Http\Controllers\Admin\VouchersController;
use App\Http\Controllers\Admin\LeadershipTypeController;
use App\Http\Controllers\Admin\SponsorCategoryTypeController;
use App\Http\Controllers\Admin\LeftLogoController;
use App\Http\Controllers\Admin\RightLogoController;
use App\Http\Controllers\Admin\HomePage\ProgramController;
use App\Http\Controllers\Admin\HomePage\EventController;
use App\Http\Controllers\Admin\HomePage\ScheduleController;
use App\Http\Controllers\Admin\HomePage\DonorController;
use App\Http\Controllers\Admin\HomePage\VideoController;
use App\Http\Controllers\Admin\HomePage\MemberController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\AdminRegistrationController;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\RegistrationController;
use App\Http\Controllers\Admin\PaymenttypeController;
use App\Http\Controllers\Admin\SponsorCategoryController;
use App\Http\Controllers\Admin\PaymentController;
use App\Http\Controllers\Admin\BenefittypeController;
use App\Http\Controllers\Admin\CommitteController;
use App\Http\Controllers\Admin\ExhibitorTypeController;
use App\Http\Controllers\Auth\RegisteredUserController;
use App\Http\Controllers\SouvenirRegistrationController;

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', [HomeController::class, 'index'] );
Route::get('otp_send', [RegisteredUserController::class, 'send_verify_email']);
Route::post('new_registertion', [RegisteredUserController::class, 'new_registertion']);
Route::post('update_password', [RegisteredUserController::class, 'update_password']);


Route::get('convention_details', function () {
   return view('convention_details');});

Route::get('forgotpassword', function () {
   return view('auth.forgotpassword');});

 Route::get('exhibits-registration-export', [AdminRegistrationController::class, 'ExhibitRegistrationsExport']);
 Route::get('cruise-registration-export', [AdminRegistrationController::class, 'CruiseRegistrationsExport']);

Route::get('convention-registration-export', [AdminRegistrationController::class, 'ConventionRegistrationsExport']);
Route::get('satamanam-bhavati-registration-export', [AdminRegistrationController::class, 'satamanamBhavatiRegistrationsExport']);





Route::prefix('admin')->middleware(['admin', 'auth'])->group(function () {


    Route::get('/', [DashboardController::class, 'index'] );

    Route::resource('banner', BannerController::class);
    Route::put('banner-status-update', [BannerController::class ,'updateStatus']);

    Route::resource('venue', VenueController::class);

    Route::resource('message', MessageController::class);
    Route::put('message-status-update', [MessageController::class , 'updateStatus']);

    Route::resource('menu', MenuController::class);
    Route::put('menu-status-update', [MenuController::class, 'updateStatus']);

    Route::resource('submenu', SubMenuController::class);
    Route::put('submenu-status-update', [SubMenuController::class, 'updateStatus']);
    Route::get('get-submenu-with-menu/{id}/{edit?}', [SubMenuController::class, 'GetSubmenuWithMenu']);

    Route::resource('page', PageController::class);
    Route::put('page-status-update', [PageController::class, 'updateStatus']);

    Route::resource('donor', DonorController::class);
    Route::put('donor-status-update', [DonorController::class, 'updateStatus']);

    Route::post('donorImport', [RegistrationController::class, 'ImportRegesterUserStore']);
    Route::get('importMemberMail', [RegistrationController::class, 'importMemberMail']);

    Route::resource('video', VideoController::class);
    Route::put('video-status-update', [VideoController::class, 'updateStatus']);

    Route::resource('member', MemberController::class);
    Route::put('member-status-update', [MemberController::class, 'updateStatus']);
    Route::get('assigne-roles/{id}', [MemberController::class, 'showAssigneRolesPage']);
    Route::post('store-assigne-roles', [MemberController::class, 'storeAssigneRolesPage']);

    // master routes
    Route::resource('designation', DesignationController::class);
    Route::put('designation-status-update', [DesignationController::class, 'updateStatus']);

    Route::resource('donortype', DonortypeController::class);
    Route::put('donortype-status-update', [DonortypeController::class, 'updateStatus']);

    Route::resource('invitee', InviteeController::class);
    Route::put('invitee-status-update', [InviteeController::class, 'updateStatus']);

    Route::resource('vouchers', VouchersController::class);
    Route::put('vouchers-status-update', [VouchersController::class, 'updateStatus']);

    Route::resource('leadership-type', LeadershipTypeController::class);
    Route::put('leadership-type-status-update', [LeadershipTypeController::class, 'updateStatus']);

    Route::resource('sponsor-category-type', SponsorCategoryTypeController::class);
    Route::put('sponsor-category-type-status-update', [SponsorCategoryTypeController::class, 'updateStatus']);

    Route::resource('left-logo', LeftLogoController::class);
    Route::put('left-logo-status-update', [LeftLogoController::class, 'updateStatus']);
    Route::resource('right-logo', RightLogoController::class);
    Route::put('right-logo-status-update', [RightLogoController::class, 'updateStatus']);

    Route::resource('program', ProgramController::class);
    Route::put('program-status-update', [ProgramController::class, 'updateStatus']);

    Route::resource('event', EventController::class);
    Route::put('event-status-update', [EventController::class, 'updateStatus']);

    Route::resource('schedule', ScheduleController::class);

    Route::resource('sponsor-category', SponsorCategoryController::class);
    Route::put('sponsor-category-status-update', [SponsorCategoryController::class, 'updateStatus']);

    Route::resource('paymenttype', PaymenttypeController::class);
    Route::put('paymenttype-status-update', [PaymenttypeController::class, 'updateStatus']);

    Route::resource('benefittype', BenefittypeController::class);
    Route::put('benefittype-status-update', [BenefittypeController::class, 'updateStatus']);

    Route::resource('committe', CommitteController::class);
    Route::put('committe-status-update', [CommitteController::class, 'updateStatus']);

    Route::resource('exhibitor-type', ExhibitorTypeController::class);
    Route::put('exhibitor-type-status-update', [ExhibitorTypeController::class, 'updateStatus']);



    Route::get('registrations', [RegistrationController::class, 'showRegistrations']);
    Route::get('assigne-features/{id}', [RegistrationController::class, 'showAssigneFeatures']);
    Route::put('assigne-features-update', [RegistrationController::class, 'updateAssigneFeatures']);
    Route::get('exhibit-registrations', [AdminRegistrationController::class, 'exhibitRegistrations']);
    Route::get('cruise_registrations', [AdminRegistrationController::class, 'cruiseRegistrations']);

    Route::get('youth-activities-registrations', [AdminRegistrationController::class, 'youthActivitiesRegistrations']);

    Route::get('add-note/{id}', [RegistrationController::class, 'showAddNoteForm']);
    Route::post('add-note', [RegistrationController::class, 'storeAddNoteForm'])->name('registration.addnote');

    Route::get('payment-history/{user_id}', [RegistrationController::class, 'adminSidePaymentHistory']);
    Route::put('update-payment-status/{payment_id}', [PaymentController::class, 'updatePaymentStatus']);
     Route::put('update-cruisepayment-status/{id}', [PaymentController::class, 'updatecruisepaymentStatus']);
    Route::get('downlode-banner-image/{id}', [RegistrationController::class, 'download']);
    
});


 Route::get('private_convention_members', [AdminRegistrationController::class, 'private_convention_members']);
 Route::get('private_exhibits_members', [AdminRegistrationController::class, 'private_exhibits_members']);

 Route::prefix('admin')->middleware(['admin'])->group(function () {
     Route::get('add-note/{id}', [RegistrationController::class, 'showAddNoteForm']);
    Route::post('add-note', [RegistrationController::class, 'storeAddNoteForm'])->name('registration.addnote');
     Route::get('payment-history/{user_id}', [RegistrationController::class, 'adminSidePaymentHistory']);
      Route::put('update-payment-status/{payment_id}', [PaymentController::class, 'updatePaymentStatus']);
     Route::get('assigne-features/{id}', [RegistrationController::class, 'showAssigneFeatures']);
    Route::put('assigne-features-update', [RegistrationController::class, 'updateAssigneFeatures']);
    Route::get('update_notes', [RegistrationController::class, 'update_notes']);
    Route::get('update_tickets', [RegistrationController::class, 'update_tickets']);
    Route::get('auditlogs', [HomeController::class, 'auditLogs']);
 });

Route::get('reload-captcha', [HomeController::class, 'reloadCaptcha']);

Route::get('payment', [PaymentController::class, 'index']);
Route::get('payment/status', [PaymentController::class, 'status'])->name('payment.status');

app/Models/Admin/Event.php
<?php

namespace App\Models\Admin;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Event extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = "tta_2022_events";
    protected $fillable = [
        'event_name',
        'from_date',
        'to_date',
        'description',
        'image_url',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'from_date' => 'date:Y-m-d' ,
        'to_date' => 'date:Y-m-d',
    ];



    public function schedules()
    {
        return $this->hasMany(\App\Models\Admin\Schedule::class);
    }
}

app/Http/Controllers/Admin/HomePage/EventController.php
<?php

namespace App\Http\Controllers\Admin\HomePage;

use App\Http\Controllers\Controller;
use App\Http\Requests\EventStoreRequest;
use App\Http\Requests\EventUpdateRequest;
use App\Models\Admin\Event;
use App\Models\Admin\Venue;
use Illuminate\Http\Request;

class EventController extends Controller
{
    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $events = Event::withCount('schedules')->get();

        return view('admin.homePageContentUpdate.event.index', compact('events'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $venue = Venue::first();
        return view('admin.homePageContentUpdate.event.create', compact('venue'));
    }

    /**
     * @param \App\Http\Requests\EventStoreRequest $request
     * @return \Illuminate\Http\Response
     */
    public function store(EventStoreRequest $request)
    {

        $event = Event::create(array_merge($request->all(), ['image_url' => 'null']));

        $file_name = 'event' . '_' . $event->id . '.' . $request->image->getClientOriginalExtension();
        UploadFile(config('conventions.event_upload'), $request->file('image'), $file_name);

        Event::where('id', $event->id)->update(['image_url' => $file_name]);

        $request->session()->flash('event.id', $event->id);

        return redirect()->route('event.index');
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Admin\Event $event
     * @return \Illuminate\Http\Response
     */
    public function show(Request $request, Event $event)
    {
        return view('admin.homePageContentUpdate.event.show', compact('event'));
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Admin\Event $event
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Event $event)
    {
        $venue = Venue::first();
        return view('admin.homePageContentUpdate.event.edit', compact('event', 'venue'));
    }

    /**
     * @param \App\Http\Requests\EventUpdateRequest $request
     * @param \App\Models\Admin\Event $event
     * @return \Illuminate\Http\Response
     */
    public function update(EventUpdateRequest $request, Event $event)
    {
        $event->update($request->validated());

        if ($request->hasFile('image')) {

            $file_name = 'event' . '_' . $event->id . '.' . $request->image->getClientOriginalExtension();
            $request->file('image')->storeAs(config('conventions.event_upload'), $file_name);

            Event::where('id', $event->id)->update(['image_url' => $file_name]);
        }

        $request->session()->flash('event.id', $event->id);

        return redirect()->route('event.index');
    }

    /**
     * @param \Illuminate\Http\Request $request
     * @param \App\Models\Admin\Event $event
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Event $event)
    {
        return $event->delete();
    }

    public function updateStatus(Request $request)
    {
        return Event::where('id', $request->id)->update(['status' => $request->status]);
    }
}

resources/views/admin/homePageContentUpdate/event/create.blade.php
@extends('layouts.admin.base')
@section('content')


<div class="page-header">
    <div class="row">
        <div class="col-9 col-sm-6 my-auto">
            <h5 class="page-title mb-0">Add Event</h5>
        </div>
        <div class="col-3 col-sm-6 col-md-6 my-auto">
            <div class="float-right">
                <a href="{{route('program.create')}}" data-toggle="tooltip" title="" class="btn back-btn" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
            </div>
        </div>
    </div>
</div>

<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('event.store')}}" method="post" enctype="multipart/form-data">
                    @csrf

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Event Name <span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="text" class="form-control" value="{{old('event_name')}}" name="event_name">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Event From Date<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="date" class="form-control" min="{{ $venue->Event_date_time->format('Y-m-d') }}" max="{{ $venue->end_date->format('Y-m-d') }}" name="from_date">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Event To Date<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="date" class="form-control" min="{{ $venue->Event_date_time->format('Y-m-d') }}" max="{{ $venue->end_date->format('Y-m-d') }}" value="{{old('to_date')}}" name="to_date">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Description<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <textarea name="description"> {{old('description')}}</textarea>
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Upload Event Image <span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="file" class="form-control" name="image">
                            <b>Image should be in 2:1 ration eg: 370X185</b>
                        </div>
                    </div>

                    <div class="text-right">
                        <input class="btn btn-primary" type="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section('javascript')


<script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>


<script>
    CKEDITOR.replace('description');
</script>



@endsection


@endsection

resources/views/admin/homePageContentUpdate/event/edit.blade.php
@extends('layouts.admin.base')
@section('content')


<div class="page-header">
    <div class="row">
        <div class="col-9 col-sm-6 my-auto">
            <h5 class="page-title mb-0">Edit Event</h5>
        </div>
        <div class="col-3 col-sm-6 col-md-6 my-auto">
            <div class="float-right">
                <a href="{{ url()->previous() }}" data-toggle="tooltip" title="" class="btn back-btn" data-original-title="Cancel"><i class="fa fa-reply"></i></a>
            </div>
        </div>
    </div>
</div>

<!-- /Page Header -->

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-body">
                <form action="{{route('event.update', $event->id )}}" method="post" enctype="multipart/form-data">
                    @csrf
                    {{ method_field('PATCH') }}

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Event Name <span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="text" class="form-control" value="{{$event->event_name}}" name="event_name">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Event From Date<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="date" class="form-control" min="{{ $venue->Event_date_time->format('Y-m-d') }}" max="{{ $venue->end_date->format('Y-m-d') }}" value="{{ \Carbon\Carbon::parse($event->from_date)->isoFormat('Y-MM-DD')}}" name="from_date">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Event To Date<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="date" class="form-control" min="{{ $venue->Event_date_time->format('Y-m-d') }}" max="{{ $venue->end_date->format('Y-m-d') }}" value="{{ \Carbon\Carbon::parse($event->to_date)->isoFormat('Y-MM-DD')}}" name="to_date">
                        </div>
                    </div>

                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Description<span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <textarea name="description">{{$event->description}}</textarea>
                        </div>
                    </div>



                    <div class="form-group row">
                        <label class="col-form-label col-md-4 my-auto">Upload Event Image <span class="mandatory">*</span></label>
                        <div class="col-md-8 my-auto">
                            <input type="file" class="form-control" name="image">
                            <b>Image should be in 2:1 ration eg: 370X185</b>
                        </div>
                    </div>
                    <img src="{{asset(config('conventions.event_display').$event->image_url)}}" alt="event" width=100 class="img-fluid">
                    <div class="text-right">
                        <input class="btn btn-primary" type="submit" name="submit" value="Submit">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section('javascript')

<script src="https://cdn.ckeditor.com/4.16.1/standard/ckeditor.js"></script>


<script>
    CKEDITOR.replace('description');
</script>


@endsection

@endsection

resources/views/admin/homePageContentUpdate/event/index.blade.php
@extends('layouts.admin.base')
@section('content')


<!-- Page Header -->

<div class="page-header">
    <div class="row">
        <div class="col-9 col-sm-6 my-auto">
            <h5 class="page-title mb-0">Events</h5>
        </div>
        <div class="col-3 col-sm-6 col-md-6 my-auto">
            <div class="float-right">
                <a href="{{route('event.create')}}" title="" class="add-new-btn btn" data-original-title="Add New"><i class="fa fa-plus"></i></a>
            </div>
        </div>
    </div>
</div>

<!-- /Page Header -->

<div class="row">
    <div class="col-md-12">
        <div class="card">
            <div class="card-body">
                <div class="table-responsive">
                    <table class="datatable table table-hover table-center mb-0">
                        <thead>
                            <tr>
                                <th>Sl NO.</th>
                                <th>Name</th>
                                <th>From - To Dates</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse($events as $event)
                            <tr>
                                <td>{{$loop->iteration}}</td>
                                <td>{{$event->event_name}}</td>
                                <td>{{ \Carbon\Carbon::parse($event->from_date)->isoFormat('MMM Do YYYY')}} To {{ \Carbon\Carbon::parse($event->to_date)->isoFormat('MMM Do YYYY')}} </td>
                                <td>
                                    <a href="{{route('event.edit', $event->id)}}" class="btn btn-sm btn-success text-white my-1 mx-1">Edit</a>
                                    <button href="#" {{$event->schedules_count==0 ? '': 'disabled' }} data-id={{$event->id}} data-url='{{ env("APP_URL") }}/admin/event/{{$event->id}}' class="btn btn-sm btn-success my-1 mx-1  delete-btn">Delete</button>
                                    <a href="{{url('admin/schedule/create')}}?event={{$event->id}}" class="btn btn-sm btn-success my-1 mx-1 ">Add schedule</a>
                                     <button href="#" data-url="{{ env("APP_URL") }}/admin/event-status-update" class="btn btn-sm btn-success text-white my-1 mx-1 status-btn" data-id={{$event->id}}>{{ $event->status=='1' ?  'Active': 'InActive' }}</button>
                                </td>
                            </tr>
                            @empty
                            <p>No donortypes to Show</p>
                            @endforelse

                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

@section('javascript')


@endsection



@endsection

resources/views/admin/homePageContentUpdate/event/show.blade.php
{{--
    @extends('layouts.app')

    @section('content')
        event.show template
    @endsection
--}}